export const foundationList = [
    { name: 'About', path: '/documentation/foundation/about' },
    { name: 'Philosophy', path: '/documentation/foundation/philosophy' },
];

export const componentsList = [
    { name: 'Accordion', path: '/documentation/components/accordion' },
    { name: 'Alert', path: '/documentation/components/alert' },
    { name: 'AlertDialog', path: '/documentation/components/alert-dialog' },
    { name: 'Avatar', path: '/documentation/components/avatar' },
    { name: 'Badge', path: '/documentation/components/badge' },
    { name: 'Breadcrumbs', path: '/documentation/components/breadcrumbs' },
    { name: 'Button', path: '/documentation/components/button' },
    { name: 'Card', path: '/documentation/components/card' },
    { name: 'Carousel', path: '/documentation/components/carousel' },
    { name: 'Checkbox', path: '/documentation/components/checkbox' },
    { name: 'Collapse', path: '/documentation/components/collapse' },
    { name: 'Dialog', path: '/documentation/components/dialog' },
    { name: 'Dropdown', path: '/documentation/components/dropdown' },
    { name: 'Error', path: '/documentation/components/error' },
    { name: 'Footer', path: '/documentation/components/footer' },
    { name: 'Header', path: '/documentation/components/header' },
    { name: 'Input', path: '/documentation/components/input' },
    { name: 'List', path: '/documentation/components/list' },
    { name: 'Modal', path: '/documentation/components/modal' },
    { name: 'Navbar', path: '/documentation/components/navbar' },
    { name: 'Notification', path: '/documentation/components/notification' },
    { name: 'ProgressBar', path: '/documentation/components/progress-bar' },
    { name: 'ProgressTracker', path: '/documentation/components/progress-tracker' },
    { name: 'RadioButton', path: '/documentation/components/radio-button' },
    { name: 'Rating', path: '/documentation/components/rating' },
    { name: 'SearchBar', path: '/documentation/components/search-bar' },
    { name: 'Select', path: '/documentation/components/select' },
    { name: 'SkeletonLoader', path: '/documentation/components/skeleton-loader' },
    { name: 'Slider', path: '/documentation/components/slider' },
    { name: 'Snackbar', path: '/documentation/components/snackbar' },
    { name: 'Spinner', path: '/documentation/components/spinner' },
    { name: 'StatusDot', path: '/documentation/components/status-dot' },
    { name: 'Stepper', path: '/documentation/components/stepper' },
    { name: 'Snippet', path: '/documentation/components/snippet' },
    { name: 'Switch', path: '/documentation/components/switch' },
    { name: 'Tabs', path: '/documentation/components/tabs' },
    { name: 'TextArea', path: '/documentation/components/text-area' },
    { name: 'Toggle', path: '/documentation/components/toggle' },
    { name: 'Tooltip', path: '/documentation/components/tooltip' },
];