export const aboutList = [
    { name: 'About Astra UI', path: '/about' },
];

export const foundationList = [
    { name: 'A11y', path: '/foundations/accessibility' },
    { name: 'Brand expression', path: '/foundations/brand' },
    { name: 'Color', path: '/foundations/color' },
    { name: 'Content standards', path: '/foundations/content' },
    { name: 'Data visualization', path: '/foundations/data-visualization' },
    { name: 'Philosophy', path: '/foundations/philosophy' },
    { name: 'Screen sizes', path: '/foundations/screen-sizes' },
    { name: 'Typography', path: '/foundations/typography' },
];

export const componentsList = [
    { name: 'Accordion', path: '/components/accordion' },
    { name: 'Alert', path: '/components/alert' },
    { name: 'AlertDialog', path: '/components/alert-dialog' },
    { name: 'Avatar', path: '/components/avatar' },
    { name: 'Badge', path: '/components/badge' },
    { name: 'Breadcrumbs', path: '/components/breadcrumbs' },
    { name: 'Button', path: '/components/button' },
    { name: 'Card', path: '/components/card' },
    { name: 'Carousel', path: '/components/carousel' },
    { name: 'Checkbox', path: '/components/checkbox' },
    { name: 'Collapse', path: '/components/collapse' },
    { name: 'Dialog', path: '/components/dialog' },
    { name: 'Dropdown', path: '/components/dropdown' },
    { name: 'Error', path: '/components/error' },
    { name: 'Footer', path: '/components/footer' },
    { name: 'Header', path: '/components/header' },
    { name: 'Input', path: '/components/input' },
    { name: 'List', path: '/components/list' },
    { name: 'Modal', path: '/components/modal' },
    { name: 'Navbar', path: '/components/navbar' },
    { name: 'Notification', path: '/components/notification' },
    { name: 'ProgressBar', path: '/components/progress-bar' },
    { name: 'ProgressTracker', path: '/components/progress-tracker' },
    { name: 'RadioButton', path: '/components/radio-button' },
    { name: 'Rating', path: '/components/rating' },
    { name: 'SearchBar', path: '/components/search-bar' },
    { name: 'Select', path: '/components/select' },
    { name: 'SkeletonLoader', path: '/components/skeleton-loader' },
    { name: 'Slider', path: '/components/slider' },
    { name: 'Snackbar', path: '/components/snackbar' },
    { name: 'Snippet', path: '/components/snippet' },
    { name: 'Spinner', path: '/components/spinner' },
    { name: 'StatusDot', path: '/components/status-dot' },
    { name: 'Stepper', path: '/components/stepper' },
    { name: 'Switch', path: '/components/switch' },
    { name: 'Tabs', path: '/components/tabs' },
    { name: 'TextArea', path: '/components/text-area' },
    { name: 'Toggle', path: '/components/toggle' },
    { name: 'Tooltip', path: '/components/tooltip' },
];