export const foundationList = [
    { name: 'About', path: '/documentation/foundation/about' },
    { name: 'Philosophy', path: '/documentation/foundation/philosophy' },
];

export const componentsList = [
    { name: 'Accordion', path: '/documentation/components/accordion' },
    { name: 'Alert', path: '/documentation/components/alert' },
    { name: 'AlertDialog', path: '/documentation/components/alert-dialog' },
    { name: 'Avatar', path: '/documentation/components/avatar' },
    { name: 'Badge', path: '/documentation/components/badge' },
    { name: 'Button', path: '/documentation/components/button' },
    { name: 'Card', path: '/documentation/components/card' },
    { name: 'Checkbox', path: '/documentation/components/checkbox' },
    { name: 'Collapse', path: '/documentation/components/collapse' },
    { name: 'Dialog', path: '/documentation/components/dialog' },
    { name: 'Dropdown', path: '/documentation/components/dropdown' },
    { name: 'Footer', path: '/documentation/components/footer' },
    { name: 'Input', path: '/documentation/components/input' },
    { name: 'Layout', path: '/documentation/components/layout' },
    { name: 'List', path: '/documentation/components/list' },
    { name: 'Modal', path: '/documentation/components/modal' },
    { name: 'Navbar', path: '/documentation/components/navbar' },
    { name: 'Notification', path: '/documentation/components/notification' },
    { name: 'ProgressBar', path: '/documentation/components/progressbar' },
    { name: 'ProgressTracker', path: '/documentation/components/progresstracker' },
    { name: 'RadioButton', path: '/documentation/components/radiobutton' },
    { name: 'Rating', path: '/documentation/components/rating' },
    { name: 'SearchBar', path: '/documentation/components/search-bar' },
    { name: 'Select', path: '/documentation/components/select' },
    { name: 'Slider', path: '/documentation/components/slider' },
    { name: 'Spinner', path: '/documentation/components/spinner' },
    { name: 'Stepper', path: '/documentation/components/stepper' },
    { name: 'Switch', path: '/documentation/components/switch' },
    { name: 'Tabs', path: '/documentation/components/tabs' },
    { name: 'TextArea', path: '/documentation/components/textarea' },
    { name: 'Toggle', path: '/documentation/components/toggle' },
];